/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FeynmanPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// local-secrets.ts
var LOCAL_SECRETS = {
  apiKey: "",
  serpApiKey: ""
};

// settings.ts
var DEFAULT_SETTINGS = {
  aiProvider: "deepseek",
  apiKey: LOCAL_SECRETS.apiKey,
  modelName: "deepseek-chat",
  customEndpoint: "",
  serpApiKey: LOCAL_SECRETS.serpApiKey,
  searchEngine: "baidu",
  searchRegion: "cn",
  searchLanguage: "zh-cn",
  searchResultsCount: 10,
  seoOutputDirectory: "SEO Briefs",
  learningDirectory: "Learning",
  defaultLearningDepth: "medium",
  lowScoreInterval: 1,
  mediumScoreInterval: 7,
  highScoreInterval: 14,
  lowScoreThreshold: 70,
  mediumScoreThreshold: 85
};
var PROVIDER_CONFIGS = {
  openai: {
    name: "OpenAI",
    defaultModel: "gpt-4",
    endpoint: "https://api.openai.com/v1/chat/completions"
  },
  claude: {
    name: "Claude",
    defaultModel: "claude-3-sonnet-20240229",
    endpoint: "https://api.anthropic.com/v1/messages"
  },
  deepseek: {
    name: "Deepseek",
    defaultModel: "deepseek-chat",
    endpoint: "https://api.deepseek.com/v1/chat/completions"
  },
  qwen: {
    name: "\u901A\u7FA9\u5343\u554F (Qwen)",
    defaultModel: "qwen-turbo",
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
  },
  baidu: {
    name: "\u6587\u5FC3\u4E00\u8A00 (ERNIE)",
    defaultModel: "ernie-bot-turbo",
    endpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions"
  },
  custom: {
    name: "Custom Endpoint",
    defaultModel: "",
    endpoint: ""
  }
};

// settings-tab.ts
var import_obsidian = require("obsidian");
var FeynmanSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "SEO Outline Generator Settings" });
    new import_obsidian.Setting(containerEl).setName("AI provider").setDesc("Recommended: DeepSeek. Custom is supported for OpenAI-compatible endpoints.").addDropdown((dropdown) => {
      Object.entries(PROVIDER_CONFIGS).forEach(([key, config]) => {
        dropdown.addOption(key, config.name);
      });
      dropdown.setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
        this.plugin.settings.aiProvider = value;
        this.plugin.settings.modelName = PROVIDER_CONFIGS[value].defaultModel;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName("AI API key").setDesc("DeepSeek API key or the key required by the selected provider.").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Model name").setDesc("DeepSeek default is deepseek-chat.").addText((text) => text.setPlaceholder(PROVIDER_CONFIGS[this.plugin.settings.aiProvider].defaultModel).setValue(this.plugin.settings.modelName).onChange(async (value) => {
      this.plugin.settings.modelName = value.trim();
      await this.plugin.saveSettings();
    }));
    if (this.plugin.settings.aiProvider === "custom") {
      new import_obsidian.Setting(containerEl).setName("Custom endpoint").setDesc("OpenAI-compatible chat completions endpoint.").addText((text) => text.setPlaceholder("https://api.example.com/v1/chat/completions").setValue(this.plugin.settings.customEndpoint).onChange(async (value) => {
        this.plugin.settings.customEndpoint = value.trim();
        await this.plugin.saveSettings();
      }));
    }
    containerEl.createEl("h3", { text: "SERP Search" });
    new import_obsidian.Setting(containerEl).setName("SerpApi key").setDesc("Used to fetch live top results before sending context to DeepSeek.").addText((text) => text.setPlaceholder("your-serpapi-key").setValue(this.plugin.settings.serpApiKey).onChange(async (value) => {
      this.plugin.settings.serpApiKey = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Search engine").setDesc("Baidu is recommended for Chinese mainland SEO. Google remains available.").addDropdown((dropdown) => {
      dropdown.addOption("baidu", "Baidu");
      dropdown.addOption("google", "Google");
      dropdown.setValue(this.plugin.settings.searchEngine).onChange(async (value) => {
        this.plugin.settings.searchEngine = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Search region").setDesc("Examples: cn, us. Passed through to SerpApi as the market hint.").addText((text) => text.setPlaceholder("cn").setValue(this.plugin.settings.searchRegion).onChange(async (value) => {
      this.plugin.settings.searchRegion = value.trim() || "cn";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Search language").setDesc("Examples: zh-cn, en. Passed to the search request when supported.").addText((text) => text.setPlaceholder("zh-cn").setValue(this.plugin.settings.searchLanguage).onChange(async (value) => {
      this.plugin.settings.searchLanguage = value.trim() || "zh-cn";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Result count").setDesc("How many live search results to include in the context.").addText((text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.searchResultsCount)).onChange(async (value) => {
      const count = Number.parseInt(value, 10);
      if (!Number.isNaN(count) && count > 0 && count <= 20) {
        this.plugin.settings.searchResultsCount = count;
        await this.plugin.saveSettings();
      }
    }));
    containerEl.createEl("h3", { text: "Output" });
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Generated SEO briefs and outlines will be saved here.").addText((text) => text.setPlaceholder("SEO Briefs").setValue(this.plugin.settings.seoOutputDirectory).onChange(async (value) => {
      this.plugin.settings.seoOutputDirectory = value.trim() || "SEO Briefs";
      await this.plugin.saveSettings();
    }));
  }
};

// ui/sidebar.ts
var import_obsidian5 = require("obsidian");

// api/llm-service.ts
var LLMError = class extends Error {
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode;
    this.name = "LLMError";
  }
};
function validateSeoOutlineResult(data) {
  if (!data || typeof data !== "object") {
    throw new LLMError("Invalid response: not an object");
  }
  if (typeof data.keyword !== "string" || typeof data.keywordType !== "string" || typeof data.titleSuggestion !== "string") {
    throw new LLMError("Invalid response: missing keyword metadata");
  }
  if (!Array.isArray(data.logicChain) || !Array.isArray(data.outline) || !Array.isArray(data.gapAnalysis)) {
    throw new LLMError("Invalid response: missing arrays");
  }
  if (!data.brief || typeof data.brief !== "object") {
    throw new LLMError("Invalid response: missing brief");
  }
  return data;
}

// core/file-generator.ts
var import_obsidian2 = require("obsidian");

// utils/helpers.ts
function generateTimestamp() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  const hours = String(now.getHours()).padStart(2, "0");
  const minutes = String(now.getMinutes()).padStart(2, "0");
  const seconds = String(now.getSeconds()).padStart(2, "0");
  return `${year}-${month}-${day}-${hours}${minutes}${seconds}`;
}
function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function sanitizeFilename(filename) {
  return filename.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, "-").replace(/-+/g, "-").trim();
}
function calculateReviewDate(score, baseDate) {
  let daysToAdd;
  if (score < 70) {
    daysToAdd = 1;
  } else if (score < 85) {
    daysToAdd = 7;
  } else {
    daysToAdd = 14;
  }
  const reviewDate = new Date(baseDate);
  reviewDate.setDate(reviewDate.getDate() + daysToAdd);
  return reviewDate;
}

// core/file-generator.ts
var FileGenerator = class {
  constructor(app, learningDirectory) {
    this.app = app;
    this.learningDirectory = learningDirectory;
  }
  updateOutputDirectory(directory) {
    this.learningDirectory = directory;
  }
  /**
   * Generate a markdown file for the learning record
   */
  async generateFile(concept, explanation, analysis, depth) {
    const { subject, understanding_score, gaps, analysis_summary } = analysis;
    const subjectDir = `${this.learningDirectory}/${subject}`;
    await this.ensureDirectoryExists(subjectDir);
    const timestamp = generateTimestamp();
    const sanitizedConcept = sanitizeFilename(concept);
    const filename = `${sanitizedConcept}-${timestamp}.md`;
    const filepath = `${subjectDir}/${filename}`;
    const today = new Date();
    const reviewDate = calculateReviewDate(understanding_score, today);
    const content = this.generateMarkdownContent(
      concept,
      subject,
      today,
      understanding_score,
      explanation,
      analysis_summary,
      gaps,
      reviewDate,
      depth
    );
    const file = await this.app.vault.create(filepath, content);
    return file;
  }
  generateMarkdownContent(concept, subject, date, score, explanation, summary, gaps, reviewDate, depth) {
    const dateStr = formatDate(date);
    const reviewDateStr = formatDate(reviewDate);
    const depthLabels = {
      shallow: "\u6DFA\u5C64",
      medium: "\u4E2D\u5C64",
      deep: "\u6DF1\u5C64"
    };
    return `# ${concept}

**\u5B78\u79D1\uFF1A** ${subject}
**\u5B78\u7FD2\u6DF1\u5EA6\uFF1A** ${depthLabels[depth]}
**\u65E5\u671F\uFF1A** ${dateStr}
**\u7406\u89E3\u5EA6\u8A55\u5206\uFF1A** ${score}/100

## \u4F60\u7684\u8B1B\u89E3
${explanation}

## \u5206\u6790\u7D50\u679C
${summary}

## \u767C\u73FE\u7684\u7F3A\u53E3
${gaps.map((gap) => `- ${gap}`).join("\n")}

## \u4E0B\u6B21\u8907\u7FD2\u6642\u9593\uFF08\u5EFA\u8B70\uFF09
${reviewDateStr}
`;
  }
  async generateSeoBriefFile(keyword, analysis, serpResults) {
    await this.ensureDirectoryExists(this.learningDirectory);
    const timestamp = generateTimestamp();
    const sanitizedKeyword = sanitizeFilename(keyword);
    const filepath = `${this.learningDirectory}/${sanitizedKeyword}-${timestamp}.md`;
    const content = this.generateSeoMarkdownContent(analysis, serpResults);
    return this.app.vault.create(filepath, content);
  }
  generateSeoMarkdownContent(analysis, serpResults) {
    const dateStr = formatDate(new Date());
    return `# ${analysis.keyword}

**\u65E5\u671F\uFF1A** ${dateStr}
**\u5173\u952E\u8BCD\u7C7B\u578B\uFF1A** ${analysis.keywordType}
**\u5EFA\u8BAE\u6807\u9898\uFF1A** ${analysis.titleSuggestion}

## \u903B\u8F91\u94FE
${analysis.logicChain.map((item) => `- ${item}`).join("\n")}

## \u6587\u7AE0\u6846\u67B6
${analysis.outline.map((section, index) => `### \u7B2C${index + 1}\u6BB5\uFF1A${section.heading}
\u76EE\u6807\uFF1A${section.goal}
\u8981\u70B9\uFF1A
${section.keyPoints.map((point) => `- ${point}`).join("\n")}`).join("\n\n")}

## SEO Brief
- \u5173\u952E\u8BCD\u7C7B\u578B\uFF1A${analysis.brief.keywordType}
- \u641C\u7D22\u610F\u56FE\uFF1A${analysis.brief.searchIntent}
- \u76EE\u6807\u53D7\u4F17\uFF1A${analysis.brief.targetAudience}
- \u5185\u5BB9\u76EE\u6807\uFF1A${analysis.brief.contentGoal}
- \u8BED\u6C14\uFF1A${analysis.brief.tone}
- \u63A8\u8350\u89D2\u5EA6\uFF1A${analysis.brief.recommendedAngle}
- CTA\u65B9\u5411\uFF1A${analysis.brief.ctaDirection}

\u5FC5\u987B\u8986\u76D6\u70B9\uFF1A
${analysis.brief.mustCover.map((item) => `- ${item}`).join("\n")}

\u8865\u5145\u8BF4\u660E\uFF1A
${analysis.brief.notes.map((item) => `- ${item}`).join("\n")}

## SERP \u7F3A\u53E3\u5206\u6790
${analysis.gapAnalysis.map((item) => `- ${item}`).join("\n")}

## SERP \u5171\u6027
${analysis.serpSummary.map((item) => `- ${item}`).join("\n")}

## SERP \u6807\u9898\u53C2\u8003
${analysis.sourceTitles.map((item) => `- ${item}`).join("\n")}

## \u5B9E\u65F6\u641C\u7D22\u7ED3\u679C
${serpResults.map((item) => `### ${item.position}. ${item.title}
- \u6458\u8981\uFF1A${item.snippet || "\u65E0\u6458\u8981"}
- \u94FE\u63A5\uFF1A${item.link || "\u65E0\u94FE\u63A5"}`).join("\n\n")}
`;
  }
  /**
   * Ensure a directory exists, creating it if necessary
   */
  async ensureDirectoryExists(path) {
    const parts = path.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const folder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.app.vault.createFolder(currentPath);
      } else if (!(folder instanceof import_obsidian2.TFolder)) {
        throw new Error(`Path exists but is not a folder: ${currentPath}`);
      }
    }
  }
};

// core/seo-analyzer.ts
var import_obsidian4 = require("obsidian");

// api/prompt-templates.ts
var SEO_SYSTEM_PROMPT = `\u4F60\u662F\u4E2D\u6587SEO\u5185\u5BB9\u7B56\u7565\u7F16\u8F91\uFF0C\u8D1F\u8D23\u57FA\u4E8E\u5B9E\u65F6\u641C\u7D22\u7ED3\u679C\u751F\u6210\u4E13\u4E1A\u7684\u6587\u7AE0\u6846\u67B6\u548Cbrief\u3002

\u8981\u6C42\uFF1A
1. \u8F93\u51FA\u8BED\u8A00\u5FC5\u987B\u662F\u7B80\u4F53\u4E2D\u6587\uFF0C\u9002\u914D\u4E2D\u56FD\u5927\u9646\u3002
2. \u4E0D\u5199\u6B63\u6587\uFF0C\u53EA\u8F93\u51FA\u7ED3\u6784\u5316\u7ED3\u679C\u3002
3. \u603B\u6BB5\u6570\u4E0D\u5F97\u8D85\u8FC76\u6BB5\uFF0C\u4E0D\u80FD\u662F\u96F6\u6563\u7ED3\u6784\uFF0C\u6BCF\u4E00\u6BB5\u90FD\u8981\u627F\u62C5\u660E\u786E\u903B\u8F91\u529F\u80FD\u3002
4. \u5FC5\u987B\u7ED9\u51FA\u5B8C\u6574\u903B\u8F91\u94FE\uFF0C\u6BB5\u843D\u4E4B\u95F4\u8981\u81EA\u7136\u627F\u63A5\uFF0C\u4E0D\u80FD\u8DF3\u8DC3\u3002
5. CTA\u5FC5\u987B\u5355\u72EC\u6210\u6BB5\uFF0C\u4F46\u4E0D\u80FD\u50CF\u786C\u5E7F\uFF0C\u8981\u4E0E\u524D\u6587\u903B\u8F91\u8854\u63A5\u3002
6. \u5BF9\u57FA\u7840\u64CD\u4F5C/\u547D\u4EE4\u7C7B\u5173\u952E\u8BCD\uFF0C\u5982\u679C\u63D0\u4F9B\u4E86\u64CD\u4F5C\u6B65\u9AA4\uFF0C\u53EA\u80FD\u628A\u5B83\u5F53\u4F5C\u6821\u51C6\u53C2\u8003\uFF0C\u4E0D\u80FD\u628A\u5B8C\u6574\u64CD\u4F5C\u8FC7\u7A0B\u5199\u8FDB\u6587\u7AE0\u7ED3\u6784\u3002
7. \u82E5\u57FA\u7840\u64CD\u4F5C/\u547D\u4EE4\u7C7B\u5173\u952E\u8BCD\u672A\u63D0\u4F9B\u64CD\u4F5C\u6B65\u9AA4\uFF0C\u8981\u5728brief.notes\u4E2D\u660E\u786E\u63D0\u793A\u6B63\u5F0F\u751F\u4EA7\u524D\u9700\u8865\u5145\u6B65\u9AA4\u53C2\u8003\u3002
8. \u7ED3\u5408\u5B9E\u65F6SERP\uFF0C\u6307\u51FA\u7ADE\u54C1\u5DF2\u7ECF\u8986\u76D6\u7684\u70B9\u548C\u4ECD\u53EF\u8865\u5F3A\u7684\u7F3A\u53E3\u3002

\u8BF7\u4E25\u683C\u8F93\u51FAJSON\u5BF9\u8C61\uFF0C\u4E0D\u8981\u9644\u5E26\u89E3\u91CA\u6587\u5B57\u3002`;
function buildSeoUserPrompt(args) {
  const operationReference = args.operationSteps.trim() ? args.operationSteps.trim() : "\u7528\u6237\u6682\u672A\u63D0\u4F9B\u64CD\u4F5C\u6B65\u9AA4\u53C2\u8003\u3002";
  const extraContext = args.userContext.trim() ? args.userContext.trim() : "\u65E0\u989D\u5916\u4E1A\u52A1\u8865\u5145\u3002";
  return `\u8BF7\u57FA\u4E8E\u4EE5\u4E0B\u4FE1\u606F\uFF0C\u4E3A\u5173\u952E\u8BCD\u751F\u6210 SEO \u6587\u7AE0\u6846\u67B6\u548C brief\u3002

\u5173\u952E\u8BCD\uFF1A${args.keyword}
\u5173\u952E\u8BCD\u7C7B\u578B\uFF1A${args.keywordType}
\u641C\u7D22\u5F15\u64CE\uFF1A${args.searchEngine}
\u7528\u6237\u8865\u5145\u4FE1\u606F\uFF1A${extraContext}
\u64CD\u4F5C\u6B65\u9AA4\u53C2\u8003\uFF1A${operationReference}

\u5B9E\u65F6SERP\u524D\u5217\u7ED3\u679C\uFF1A
${args.serpResults}

\u8F93\u51FAJSON\u683C\u5F0F\u5982\u4E0B\uFF1A
{
  "keyword": "${args.keyword}",
  "keywordType": "\u5173\u952E\u8BCD\u7C7B\u578B\u5224\u65AD\u7ED3\u679C",
  "titleSuggestion": "\u5EFA\u8BAE\u6807\u9898",
  "logicChain": [
    "\u6B65\u9AA41\uFF1A\u4ECE\u4EC0\u4E48\u8BA4\u77E5\u5207\u5165",
    "\u6B65\u9AA42\uFF1A\u5982\u4F55\u627F\u63A5\u5230\u4E0B\u4E00\u6BB5"
  ],
  "outline": [
    {
      "heading": "\u6BB5\u843D\u6807\u9898",
      "goal": "\u8BE5\u6BB5\u627F\u62C5\u7684\u903B\u8F91\u76EE\u6807",
      "keyPoints": ["\u8981\u70B91", "\u8981\u70B92"]
    }
  ],
  "brief": {
    "keywordType": "\u5173\u952E\u8BCD\u7C7B\u578B",
    "searchIntent": "\u641C\u7D22\u610F\u56FE",
    "targetAudience": "\u76EE\u6807\u53D7\u4F17",
    "contentGoal": "\u5185\u5BB9\u76EE\u6807",
    "tone": "\u4E13\u4E1A",
    "recommendedAngle": "\u5EFA\u8BAE\u5199\u6CD5",
    "mustCover": ["\u5FC5\u987B\u8986\u76D6\u70B91", "\u5FC5\u987B\u8986\u76D6\u70B92"],
    "ctaDirection": "CTA\u65B9\u5411",
    "notes": ["\u8865\u5145\u8BF4\u660E1", "\u8865\u5145\u8BF4\u660E2"]
  },
  "gapAnalysis": ["SERP\u5DF2\u6709\u8986\u76D6\u70B9/\u7F3A\u53E31", "SERP\u5DF2\u6709\u8986\u76D6\u70B9/\u7F3A\u53E32"],
  "serpSummary": ["SERP\u5171\u60271", "SERP\u5171\u60272"],
  "sourceTitles": ["\u6807\u98981", "\u6807\u98982"]
}

\u7EA6\u675F\uFF1A
- outline\u6700\u591A6\u6BB5\u3002
- \u4E0D\u8981\u8F93\u51FA\u6B63\u6587\u3002
- \u6BCF\u6BB5\u5FC5\u987B\u662F\u5B8C\u6574\u903B\u8F91\u94FE\u7684\u4E00\u90E8\u5206\u3002
- CTA\u5FC5\u987B\u662Foutline\u6700\u540E\u4E00\u6BB5\u3002
- \u82E5\u5173\u952E\u8BCD\u5C5E\u4E8E\u57FA\u7840\u64CD\u4F5C/\u547D\u4EE4\u7C7B\uFF0C\u8981\u5F3A\u8C03\u201C\u6982\u5FF5/\u4EF7\u503C/\u5224\u65AD\u903B\u8F91/\u6587\u4EF6\u4E0E\u534F\u4F5C\u5EF6\u5C55/\u5E73\u53F0\u80FD\u529B/CTA\u201D\u4E2D\u7684\u9002\u914D\u94FE\u8DEF\uFF0C\u800C\u4E0D\u662F\u5199\u64CD\u4F5C\u6559\u7A0B\u3002
- \u5982\u5B9E\u65F6SERP\u666E\u904D\u7F3A\u5931\u201C\u5728\u7EBF\u534F\u4F5C\u3001AI\u534F\u52A9\u3001\u4EA7\u54C1\u7BA1\u7406\u201D\u89C6\u89D2\uFF0C\u53EF\u5728gapAnalysis\u548CrecommendedAngle\u4E2D\u660E\u786E\u63D0\u51FA\u3002`;
}

// api/serpapi-service.ts
var import_obsidian3 = require("obsidian");
var SerpApiService = class {
  constructor(settings) {
    this.settings = settings;
  }
  async search(keyword) {
    var _a;
    if (!this.settings.serpApiKey) {
      throw new LLMError("SerpApi key is not configured");
    }
    const engine = this.settings.searchEngine;
    const limit = this.settings.searchResultsCount;
    const url = new URL("https://serpapi.com/search.json");
    url.searchParams.set("api_key", this.settings.serpApiKey);
    url.searchParams.set("q", keyword);
    url.searchParams.set("engine", engine);
    url.searchParams.set("num", String(limit));
    if (engine === "google") {
      url.searchParams.set("hl", this.settings.searchLanguage);
      url.searchParams.set("gl", this.settings.searchRegion);
    } else if (engine === "baidu") {
      url.searchParams.set("rn", String(limit));
    }
    const response = await (0, import_obsidian3.requestUrl)({
      url: url.toString(),
      method: "GET",
      headers: {
        "Content-Type": "application/json"
      }
    });
    if (response.status < 200 || response.status >= 300) {
      throw new LLMError(`SerpApi error: HTTP ${response.status} - ${response.text}`, response.status);
    }
    const data = response.json;
    const results = (_a = data.organic_results) != null ? _a : [];
    return results.slice(0, limit).map((item, index) => {
      var _a2, _b, _c, _d, _e;
      return {
        position: (_a2 = item.position) != null ? _a2 : index + 1,
        title: (_b = item.title) != null ? _b : "Untitled result",
        snippet: (_c = item.snippet) != null ? _c : "",
        link: (_d = item.link) != null ? _d : "",
        source: (_e = item.displayed_link) != null ? _e : ""
      };
    });
  }
};

// core/seo-analyzer.ts
var SeoAnalyzer = class {
  constructor(settings) {
    this.settings = settings;
    this.serpApi = new SerpApiService(settings);
  }
  updateSettings(settings) {
    this.settings = settings;
    this.serpApi = new SerpApiService(settings);
  }
  async analyze(input) {
    const keyword = input.keyword.trim();
    if (!keyword) {
      throw new LLMError("Keyword cannot be empty");
    }
    if (!this.settings.apiKey) {
      throw new LLMError("AI API key is not configured");
    }
    const serpResults = await this.serpApi.search(keyword);
    if (serpResults.length === 0) {
      throw new LLMError("No live search results were returned from SerpApi");
    }
    const analysis = await this.requestOutline(input, serpResults);
    return { serpResults, analysis };
  }
  async requestOutline(input, serpResults) {
    var _a, _b, _c;
    const endpoint = this.getChatEndpoint();
    const serpBlock = serpResults.map((item) => `${item.position}. \u6807\u9898\uFF1A${item.title}
\u6458\u8981\uFF1A${item.snippet || "\u65E0\u6458\u8981"}
\u94FE\u63A5\uFF1A${item.link || "\u65E0\u94FE\u63A5"}`).join("\n\n");
    const userPrompt = buildSeoUserPrompt({
      keyword: input.keyword.trim(),
      keywordType: input.keywordType.trim() || "\u5F85\u6A21\u578B\u5224\u65AD",
      searchEngine: this.settings.searchEngine,
      userContext: input.userContext,
      operationSteps: input.operationSteps,
      serpResults: serpBlock
    });
    const response = await (0, import_obsidian4.requestUrl)({
      url: endpoint,
      method: "POST",
      headers: this.getHeaders(),
      body: JSON.stringify({
        model: this.settings.modelName,
        messages: [
          { role: "system", content: SEO_SYSTEM_PROMPT },
          { role: "user", content: userPrompt }
        ],
        response_format: { type: "json_object" },
        temperature: 0.4
      })
    });
    if (response.status < 200 || response.status >= 300) {
      throw new LLMError(`AI request failed: HTTP ${response.status} - ${response.text}`, response.status);
    }
    const data = response.json;
    const content = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
    if (!content) {
      throw new LLMError("AI response did not include any content");
    }
    try {
      return validateSeoOutlineResult(JSON.parse(content));
    } catch (error) {
      if (error instanceof LLMError) {
        throw error;
      }
      throw new LLMError("Failed to parse SEO outline response");
    }
  }
  getChatEndpoint() {
    if (this.settings.aiProvider === "custom") {
      if (!this.settings.customEndpoint) {
        throw new LLMError("Custom endpoint URL is not configured");
      }
      return this.settings.customEndpoint;
    }
    const config = PROVIDER_CONFIGS[this.settings.aiProvider];
    if (!(config == null ? void 0 : config.endpoint.includes("chat/completions"))) {
      throw new LLMError("Current provider is not supported for the SEO workflow. Use DeepSeek, OpenAI, or a custom compatible endpoint.");
    }
    return config.endpoint;
  }
  getHeaders() {
    return {
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.settings.apiKey}`
    };
  }
};

// ui/sidebar.ts
var SIDEBAR_VIEW_TYPE = "feynman-sidebar";
var SidebarView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.analyzer = new SeoAnalyzer(plugin.settings);
    this.fileGenerator = new FileGenerator(this.app, plugin.settings.seoOutputDirectory);
  }
  getViewType() {
    return SIDEBAR_VIEW_TYPE;
  }
  getDisplayText() {
    return "SEO Outline Generator";
  }
  getIcon() {
    return "file-search";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("feynman-sidebar");
    const header = container.createDiv({ cls: "feynman-header" });
    header.createEl("h3", { text: "SEO \u6587\u7AE0\u6846\u67B6\u751F\u6210" });
    header.createEl("p", {
      text: "\u5148\u7528 SerpApi \u6293\u53D6\u5B9E\u65F6 SERP\uFF0C\u518D\u628A\u6807\u9898\u548C\u6458\u8981\u4F5C\u4E3A\u4E0A\u4E0B\u6587\u53D1\u7ED9 DeepSeek\uFF0C\u8F93\u51FA\u6587\u7AE0\u6846\u67B6\u3001brief \u548C\u7F3A\u53E3\u5206\u6790\u3002",
      cls: "feynman-subtitle"
    });
    const form = container.createDiv({ cls: "feynman-form" });
    const keywordGroup = form.createDiv({ cls: "feynman-input-group" });
    keywordGroup.createEl("label", { text: "\u5173\u952E\u8BCD" });
    this.keywordInput = keywordGroup.createEl("input", {
      type: "text",
      placeholder: "\u4F8B\u5982\uFF1Acad\u955C\u50CF",
      cls: "feynman-input"
    });
    const typeGroup = form.createDiv({ cls: "feynman-input-group" });
    typeGroup.createEl("label", { text: "\u5173\u952E\u8BCD\u7C7B\u578B" });
    this.keywordTypeInput = typeGroup.createEl("input", {
      type: "text",
      placeholder: "\u4F8B\u5982\uFF1A\u57FA\u7840\u64CD\u4F5C/\u547D\u4EE4\u7C7B\u3001\u6587\u4EF6\u7C7B\u578B\u7C7B\u3001\u8D44\u6E90\u6A21\u578B\u7C7B",
      cls: "feynman-input"
    });
    const contextGroup = form.createDiv({ cls: "feynman-input-group" });
    contextGroup.createEl("label", { text: "\u4E1A\u52A1\u8865\u5145\u4FE1\u606F" });
    this.contextInput = contextGroup.createEl("textarea", {
      placeholder: "\u4F8B\u5982\uFF1A\u8BED\u8A00\u7B80\u4F53\u4E2D\u6587\uFF0C\u4E2D\u56FD\u5927\u9646\uFF0C\u8BED\u6C14\u4E13\u4E1A\uFF0CCTA \u91CD\u70B9\u662F\u5728\u7EBF\u534F\u4F5C/AI\u534F\u52A9/\u4EA7\u54C1\u7BA1\u7406\u3002",
      cls: "feynman-textarea"
    });
    this.contextInput.rows = 5;
    const stepsGroup = form.createDiv({ cls: "feynman-input-group" });
    stepsGroup.createEl("label", { text: "\u64CD\u4F5C\u6B65\u9AA4\u53C2\u8003\uFF08\u4EC5\u57FA\u7840\u64CD\u4F5C\u7C7B\u5EFA\u8BAE\u586B\u5199\uFF09" });
    this.operationStepsInput = stepsGroup.createEl("textarea", {
      placeholder: "\u4EC5\u7528\u4E8E\u6821\u51C6\u672F\u8BED\u548C\u6B65\u9AA4\u903B\u8F91\uFF0C\u4E0D\u4F1A\u628A\u5B8C\u6574\u6B65\u9AA4\u5199\u8FDB\u6587\u7AE0\u7ED3\u6784\u3002",
      cls: "feynman-textarea"
    });
    this.operationStepsInput.rows = 5;
    this.analyzeButton = form.createEl("button", {
      text: "\u751F\u6210\u6846\u67B6\u4E0E Brief",
      cls: "feynman-button"
    });
    this.analyzeButton.addEventListener("click", () => this.handleAnalyze());
    this.resultContainer = container.createDiv({ cls: "feynman-result" });
  }
  async handleAnalyze() {
    const keyword = this.keywordInput.value.trim();
    const keywordType = this.keywordTypeInput.value.trim();
    const userContext = this.contextInput.value.trim();
    const operationSteps = this.operationStepsInput.value.trim();
    if (!keyword) {
      new import_obsidian5.Notice("\u8BF7\u5148\u8F93\u5165\u5173\u952E\u8BCD");
      return;
    }
    if (!keywordType) {
      new import_obsidian5.Notice("\u8BF7\u5148\u8F93\u5165\u5173\u952E\u8BCD\u7C7B\u578B");
      return;
    }
    this.setLoading(true);
    this.resultContainer.empty();
    try {
      const output = await this.analyzer.analyze({
        keyword,
        keywordType,
        userContext,
        operationSteps
      });
      const file = await this.fileGenerator.generateSeoBriefFile(keyword, output.analysis, output.serpResults);
      this.displayResult(output.analysis, output.serpResults);
      new import_obsidian5.Notice(`\u5DF2\u751F\u6210 SEO \u6846\u67B6\u5E76\u4FDD\u5B58\u5230 ${file.path}`);
    } catch (error) {
      const message = error instanceof LLMError ? error.message : "\u751F\u6210\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5 API \u914D\u7F6E\u548C\u7F51\u7EDC\u8FDE\u63A5";
      this.displayError(message);
      new import_obsidian5.Notice(message);
    } finally {
      this.setLoading(false);
    }
  }
  setLoading(loading) {
    this.analyzeButton.disabled = loading;
    this.analyzeButton.setText(loading ? "\u6293\u53D6 SERP \u5E76\u751F\u6210\u4E2D..." : "\u751F\u6210\u6846\u67B6\u4E0E Brief");
    this.keywordInput.disabled = loading;
    this.keywordTypeInput.disabled = loading;
    this.contextInput.disabled = loading;
    this.operationStepsInput.disabled = loading;
  }
  displayResult(result, serpResults) {
    this.resultContainer.empty();
    this.resultContainer.removeClass("feynman-result-error");
    this.resultContainer.addClass("feynman-result-success");
    const titleEl = this.resultContainer.createDiv({ cls: "seo-result-title" });
    titleEl.createEl("h4", { text: result.titleSuggestion });
    titleEl.createEl("p", { text: `\u5173\u952E\u8BCD\u7C7B\u578B\uFF1A${result.keywordType}` });
    const logicEl = this.resultContainer.createDiv({ cls: "feynman-result-section" });
    logicEl.createEl("h4", { text: "\u903B\u8F91\u94FE" });
    const logicList = logicEl.createEl("ol");
    result.logicChain.forEach((item) => {
      logicList.createEl("li", { text: item });
    });
    const outlineEl = this.resultContainer.createDiv({ cls: "feynman-result-section" });
    outlineEl.createEl("h4", { text: "\u6587\u7AE0\u6846\u67B6" });
    result.outline.forEach((section, index) => {
      const block = outlineEl.createDiv({ cls: "seo-outline-block" });
      block.createEl("strong", { text: `\u7B2C${index + 1}\u6BB5\uFF1A${section.heading}` });
      block.createEl("p", { text: section.goal });
      const list = block.createEl("ul");
      section.keyPoints.forEach((point) => {
        list.createEl("li", { text: point });
      });
    });
    const briefEl = this.resultContainer.createDiv({ cls: "feynman-result-section" });
    briefEl.createEl("h4", { text: "SEO Brief" });
    const briefList = briefEl.createEl("ul");
    [
      `\u641C\u7D22\u610F\u56FE\uFF1A${result.brief.searchIntent}`,
      `\u76EE\u6807\u53D7\u4F17\uFF1A${result.brief.targetAudience}`,
      `\u5185\u5BB9\u76EE\u6807\uFF1A${result.brief.contentGoal}`,
      `\u8BED\u6C14\uFF1A${result.brief.tone}`,
      `\u63A8\u8350\u89D2\u5EA6\uFF1A${result.brief.recommendedAngle}`,
      `CTA\u65B9\u5411\uFF1A${result.brief.ctaDirection}`
    ].forEach((item) => briefList.createEl("li", { text: item }));
    const mustCoverTitle = briefEl.createEl("strong", { text: "\u5FC5\u987B\u8986\u76D6\u70B9" });
    mustCoverTitle.addClass("seo-inline-title");
    const mustCoverList = briefEl.createEl("ul");
    result.brief.mustCover.forEach((item) => mustCoverList.createEl("li", { text: item }));
    const gapEl = this.resultContainer.createDiv({ cls: "feynman-result-section" });
    gapEl.createEl("h4", { text: "SERP \u7F3A\u53E3\u5206\u6790" });
    const gapList = gapEl.createEl("ul");
    result.gapAnalysis.forEach((item) => gapList.createEl("li", { text: item }));
    const serpEl = this.resultContainer.createDiv({ cls: "feynman-result-section" });
    serpEl.createEl("h4", { text: `\u5B9E\u65F6 SERP\uFF08${serpResults.length}\u6761\uFF09` });
    serpResults.forEach((item) => {
      const block = serpEl.createDiv({ cls: "seo-serp-item" });
      block.createEl("strong", { text: `${item.position}. ${item.title}` });
      if (item.snippet) {
        block.createEl("p", { text: item.snippet });
      }
    });
  }
  displayError(message) {
    this.resultContainer.empty();
    this.resultContainer.removeClass("feynman-result-success");
    this.resultContainer.addClass("feynman-result-error");
    this.resultContainer.createEl("p", { text: message });
  }
  updateSettings() {
    this.analyzer.updateSettings(this.plugin.settings);
    this.fileGenerator.updateOutputDirectory(this.plugin.settings.seoOutputDirectory);
  }
};

// main.ts
var FeynmanPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.sidebarView = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(SIDEBAR_VIEW_TYPE, (leaf) => {
      this.sidebarView = new SidebarView(leaf, this);
      return this.sidebarView;
    });
    this.addRibbonIcon("file-search", "SEO Outline Generator", () => {
      this.activateSidebarView();
    });
    this.addCommand({
      id: "open-seo-outline-generator",
      name: "Open SEO Outline Generator",
      callback: () => this.activateSidebarView()
    });
    this.addSettingTab(new FeynmanSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.activateSidebarView();
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(SIDEBAR_VIEW_TYPE);
  }
  async loadSettings() {
    const saved = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings = {
      ...saved,
      apiKey: saved.apiKey || DEFAULT_SETTINGS.apiKey,
      serpApiKey: saved.serpApiKey || DEFAULT_SETTINGS.serpApiKey
    };
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    (_a = this.sidebarView) == null ? void 0 : _a.updateSettings();
  }
  async activateSidebarView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(SIDEBAR_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf) {
        return;
      }
      leaf = rightLeaf;
      await leaf.setViewState({
        type: SIDEBAR_VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
};
